### ISSUE TITLE
♻️ refactor: AuthenticationPrincipal refact

### ISSUE THREAD

**Issue by softwareyong** [Kakaotech-18-Ecommerce/Kakaotech-18-Server#52]
# Title
AuthenticationPrincipal refact

# TODO
- [x] buyer원래대로 @AuthenticationPrincipal로 리팩토링
- [x] seller원래대로 @AuthenticationPrincipal로 리팩토링
- [ ] cart원래대로 @AuthenticationPrincipal로 리팩토링
- [ ] product원래대로 @AuthenticationPrincipal로 리팩토링

# etc
